/**
* AUTOR: GABRIEL GAMELEIRA DOS SANTOS
* DATA: 07/09/2020
* HORA: 16: 33
* FINALIDADE DO PROGRAMA: ALTERANDO UM REGISTRO NA TABELA DE PRODUTOS 
*/

UPDATE PRODUTOS SET SABOR = 'PIZZA' WHERE COD_PRODUTO = '544931';  