/**
* AUTOR: GABRIEL GAMELEIRA DOS SANTOS
* DATA: 07/09/2020
* HORA: 15:22
* FINALIDADE DO PROGRAMA: CRIAR A TABELA DE VENDEDORES
*/

CREATE TABLE VENDEDORES (

MATRICULA VARCHAR (5) PRIMARY KEY,

NOME VARCHAR(100),

PERCENTUAL_COMISSAO SMALLINT,

);