/**
* AUTOR: GABRIEL GAMELEIRA DOS SANTOS
* DATA: 07/09/2020
* HORA: 15:43
* FINALIDADE DO PROGRAMA: EXCLUIR A TABELA CLIENTE 
*/


DROP TABLE [CLIENTE 2];

use [SUCOS_VENDAS]

GO

drop table [dbo].[CLIENTE 5];