/**
* AUTOR: GABRIEL GAMELEIRA DOS SANTOS
* DATA: 07/09/2020
* HORA: 15:43
* FINALIDADE DO PROGRAMA: SELECIONAR REGISTROS DO BANCO
*/ 

SELECT * FROM [SUCOS_VENDAS].[dbo].[TABELA DE CLIENTES];

SELECT CPF AS IDENTIFICADOR, NOME AS NOME_SOCIAL FROM [dbo].[TABELA DE CLIENTES] AS CLIENTE;

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE SABOR = 'Uva';

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE SABOR > 'Uva';

DELETE FROM [dbo].[TABELA DE PRODUTOS] WHERE SABOR = 'Limão';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO_DE_LISTA] < 10;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO_DE_LISTA] > 10;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO_DE_LISTA] <= 4.555;

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMABALAGEM <> 'Lata';

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] = '1995-09-11';

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] > '1995-09-11';

SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = '1995';

SELECT * FROM [TABELA DE CLIENTES] WHERE MONTH([DATA DE NASCIMENTO]) = '12';

SELECT * FROM [TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO]) = '11';